import { atom } from "jotai";

// ranks = 0-13, suits = 0-3

const playerHandAtom = atom([
    {
      rank: 1,
      suit: 2
    },
    {
      rank: 11,
      suit: 3
    },
    {
      rank: 12,
      suit: 0
    } 
  ]);

//  const deckAtom = atom([
//     "AC", "AD", "AH", "AS", 
//     "2C", "2D", "2H", "2S",
//     "3C", "3D", "3H", "3S",
//     "4C", "4D", "4H", "4S",
//     "5C", "5D", "5H", "5S",
//     "6C", "6D", "6H", "6S",
//     "7C", "7D", "7H", "7S",
//     "8C", "8D", "8H", "8S",
//     "9C", "9D", "9H", "9S",
//     "10C", "10D", "10H", "10S",
//     "JC", "JD", "JH", "JS",
//     "QC", "QD", "QH", "QS",
//     "KC", "KD", "KH", "KS",
//     "Joker", "Joker",
//     "AC", "AD", "AH", "AS", 
//     "2C", "2D", "2H", "2S",
//     "3C", "3D", "3H", "3S",
//     "4C", "4D", "4H", "4S",
//     "5C", "5D", "5H", "5S",
//     "6C", "6D", "6H", "6S",
//     "7C", "7D", "7H", "7S",
//     "8C", "8D", "8H", "8S",
//     "9C", "9D", "9H", "9S",
//     "10C", "10D", "10H", "10S",
//     "JC", "JD", "JH", "JS",
//     "QC", "QD", "QH", "QS",
//     "KC", "KD", "KH", "KS",
//     "Joker", "Joker",
//   ]);

  // const deckAtom = atom([
  //   "AC", "AD", "AH", "AS",
  //   "AC", "AD", "AH", "AS",
  //   "10C", "10D", "10H", "10S",
  //   "10C", "4S", "2D", "9H", "Joker"
  // ])

  const deckAtom = atom([
    { rank: 0, suit: null },
    { rank: 1, suit: 0 }, 
    { rank: 1, suit: 1 }, 
    { rank: 1, suit: 2 },
    { rank: 1, suit: 3 },
    { rank: 2, suit: 0 }, 
    { rank: 2, suit: 1 }, 
    { rank: 2, suit: 2 },
    { rank: 2, suit: 3 },
    { rank: 3, suit: 0 }, 
    { rank: 3, suit: 1 }, 
    { rank: 3, suit: 2 },
    { rank: 3, suit: 3 },
    { rank: 4, suit: 0 }, 
    { rank: 4, suit: 1 }, 
    { rank: 4, suit: 2 },
    { rank: 4, suit: 3 },
    { rank: 5, suit: 0 }, 
    { rank: 5, suit: 1 }, 
    { rank: 5, suit: 2 },
    { rank: 5, suit: 3 },
    { rank: 6, suit: 0 }, 
    { rank: 6, suit: 1 }, 
    { rank: 6, suit: 2 },
    { rank: 6, suit: 3 },
    { rank: 7, suit: 0 }, 
    { rank: 7, suit: 1 }, 
    { rank: 7, suit: 2 },
    { rank: 7, suit: 3 },
    { rank: 8, suit: 0 }, 
    { rank: 8, suit: 1 }, 
    { rank: 8, suit: 2 },
    { rank: 8, suit: 3 },
    { rank: 9, suit: 0 }, 
    { rank: 9, suit: 1 }, 
    { rank: 9, suit: 2 },
    { rank: 9, suit: 3 },
    { rank: 10, suit: 0 }, 
    { rank: 10, suit: 1 }, 
    { rank: 10, suit: 2 },
    { rank: 10, suit: 3 },
    { rank: 11, suit: 0 }, 
    { rank: 11, suit: 1 }, 
    { rank: 11, suit: 2 },
    { rank: 11, suit: 3 },
    { rank: 12, suit: 0 }, 
    { rank: 12, suit: 1 }, 
    { rank: 12, suit: 2 },
    { rank: 12, suit: 3 },
    { rank: 13, suit: 0 }, 
    { rank: 13, suit: 1 }, 
    { rank: 13, suit: 2 },
    { rank: 13, suit: 3 },
    { rank: 0, suit: null },
    { rank: 1, suit: 0 }, 
    { rank: 1, suit: 1 }, 
    { rank: 1, suit: 2 },
    { rank: 1, suit: 3 },
    { rank: 2, suit: 0 }, 
    { rank: 2, suit: 1 }, 
    { rank: 2, suit: 2 },
    { rank: 2, suit: 3 },
    { rank: 3, suit: 0 }, 
    { rank: 3, suit: 1 }, 
    { rank: 3, suit: 2 },
    { rank: 3, suit: 3 },
    { rank: 4, suit: 0 }, 
    { rank: 4, suit: 1 }, 
    { rank: 4, suit: 2 },
    { rank: 4, suit: 3 },
    { rank: 5, suit: 0 }, 
    { rank: 5, suit: 1 }, 
    { rank: 5, suit: 2 },
    { rank: 5, suit: 3 },
    { rank: 6, suit: 0 }, 
    { rank: 6, suit: 1 }, 
    { rank: 6, suit: 2 },
    { rank: 6, suit: 3 },
    { rank: 7, suit: 0 }, 
    { rank: 7, suit: 1 }, 
    { rank: 7, suit: 2 },
    { rank: 7, suit: 3 },
    { rank: 8, suit: 0 }, 
    { rank: 8, suit: 1 }, 
    { rank: 8, suit: 2 },
    { rank: 8, suit: 3 },
    { rank: 9, suit: 0 }, 
    { rank: 9, suit: 1 }, 
    { rank: 9, suit: 2 },
    { rank: 9, suit: 3 },
    { rank: 10, suit: 0 }, 
    { rank: 10, suit: 1 }, 
    { rank: 10, suit: 2 },
    { rank: 10, suit: 3 },
    { rank: 11, suit: 0 }, 
    { rank: 11, suit: 1 }, 
    { rank: 11, suit: 2 },
    { rank: 11, suit: 3 },
    { rank: 12, suit: 0 }, 
    { rank: 12, suit: 1 }, 
    { rank: 12, suit: 2 },
    { rank: 12, suit: 3 },
    { rank: 13, suit: 0 }, 
    { rank: 13, suit: 1 }, 
    { rank: 13, suit: 2 },
    { rank: 13, suit: 3 },
  ])

  const burnPileAtom = atom([
    {
      rank: 1,
      suit: 2
    }
  ]);

  export { playerHandAtom, deckAtom, burnPileAtom }